<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\DeviceMgmt.Repository\DeviceMgmt.Repository.csproj" />
    <ProjectReference Include="..\DeviceMgmt.App\DeviceMgmt.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NPOI" Version="2.7.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RootNamespace>DeviceMgmt.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="bin\**;obj\**" />
  </ItemGroup>

</Project>
